spring.datasource.url=${DB_URL:jdbc:h2:mem:ecommerce_db}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:password}
spring.jpa.properties.hibernate.dialect=${DB_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.hibernate.ddl-auto=${DB_DDL:create-drop}
spring.h2.console.enabled=true

#spring.main.allow-circular-references=true

spring.mail.host=${EMAIL_HOST:smtp.gmail.com}
spring.mail.username=${EMAIL_USERNAME:harshvirsa00@gmail.com}
spring.mail.password=${EMAIL_PASSWORD:qcodohnzwxbegvca}
spring.mail.port=${EMAIL_PORT:587}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

aws.access.key=${S3_ACCESS_KEY:AKIAYUW3V7RDPMPUII45}
aws.secret.key=${S3_SECRET_KEY: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}
aws.region=${AWS_REGION:us-east-1}
aws.s3.bucket.category=${S3_CATEGORY_BUCKET:sky-cart-category}
aws.s3.bucket.product=${S3_PRODUCT_BUCKET:sky-cart-product}
aws.s3.bucket.profile=${S3_PROFILE_BUCKET:sky-cart-profile}

server.port=${PORT:5000}
rupee.sign=${RUPEE_SIGN:&#8377;}
# INR - &#8377; #EURO : &#8364;



